version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8002:80'
    networks:
      - backend
  mysql:
    build:
      context: .
      target: mysql
    image: mysql
    container_name: mysql
    ports:
      - '33050:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '010203'
      MYSQL_DATABASE: 'recruitment'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '010203'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: UTC
    volumes:
      - ~/data/mysql2:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d2:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p010203" ]
      retries: 3
      timeout: 5s

networks:
  backend:
